{{- if .Values.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth-token: |
    {{ .Values.authToken }}
{{- end }}
